<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rh_majordomo"
 *
 * Auto generated by Extension Builder 2020-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Majordomo Plugin',
    'description' => 'A Typo3 plugin that allows a FE user to add himself to a Majordomo email list.',
    'category' => 'plugin',
    'author' => 'Rolf Huesmann',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
